# Numpy basics

#### Drawback of a list

In [37]:
height = [1.73, 1.68, 1.71, 1.89, 1.79] 
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
BMI = weight[0]/height[0]**2
print(BMI)
BMI = weight / height ** 2 # Will Throw error

21.85171572722109


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

### Numpy - Numeric Python

In [38]:
import numpy as np
np_height = np.array([1.65, 1.8, 1.45, 1.34, 1.8])
print("height", np_height)
np_weight = np.array([62.4, 55.2, 51.6, 48.4, 98.7])
print("weight", np_weight)
BMI = np_weight / np_height ** 2
print("BMI", np.round(BMI, 2)) # Will not throw error


height [1.65 1.8  1.45 1.34 1.8 ]
weight [62.4 55.2 51.6 48.4 98.7]
BMI [22.92 17.04 24.54 26.95 30.46]


#### Keep in mind


In [39]:
Array = np.array([1, 2.0, True, "hello"])
print(Array) # Will convert all elements to string
print(type(Array))

Array = np.array([1, 2.0, 3, 4]) # converts to float
print(Array) 
List = [1, 2.0, 3, 4]
print(Array + Array) #Adds elements
print(List + List) #Concatenates elements

['1' '2.0' 'True' 'hello']
<class 'numpy.ndarray'>
[1. 2. 3. 4.]
[2. 4. 6. 8.]
[1, 2.0, 3, 4, 1, 2.0, 3, 4]


#### Indexing and subsetting 1D numpy arrays

In [ ]:
Array = np.array([1, 2, 3, 4]) #1D array
print(Array[1])
print(Array[1:3])
print(Array[1:])
print(Array[:3])
print(Array>3)
print(Array[Array>2])

2
[2 3]
[2 3 4]
[1 2 3]
[False False False  True]
[3 4]


In [51]:
Array = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8]]) # 2D array
print(Array[0][2])
print(Array[0, 2])
print(Array[0, :])
print(Array[:, 2])
print(Array[:, 1:3])

3
3
[1 2 3 4]
[3 7]
[[2 3]
 [6 7]]


#### method vs attribute

In [50]:
Array = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8]]) # 2D array
print(np.mean(Array)) # Function from np module
print(Array.mean()) # Method of the array object
print(np.shape(Array)) # Attribute accessed via a method
print(Array.shape) #Directly accessing the attribute


4.5
4.5
(2, 4)
(2, 4)


#### Mathematical operations on arrays

In [59]:
Array = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8]]) # 2D array
var = np.array([3, 4, 5, 6])
print(Array * var)
print(Array * 10)
print(np.mean(Array, axis = 0)) # Column wise mean
print(np.mean(Array, axis = 1)) # Row wise mean
print(np.mean(Array, axis = None)) # Entire array mean


[[ 3  8 15 24]
 [15 24 35 48]]
[[10 20 30 40]
 [50 60 70 80]]
[3. 4. 5. 6.]
[2.5 6.5]
4.5


#### Basic statistical summary

In [70]:
Array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8]]) # 2D array  
print(np.mean(Array)) # Entire array mean
print(np.mean(Array[0, :])) # 1st row mean
print(np.mean(Array, axis = 1)) # Row wise mean
print(np.mean(Array, axis = 0)) # Column wise mean
print(np.median(Array)) # Median
print(np.std(Array)) # Standard deviation
print(np.corrcoef(Array[0, :], Array[1,:])) # Correlation coefficient between rows

4.5
2.5
[2.5 6.5]
[3. 4. 5. 6.]
4.5
2.29128784747792
[[1. 1.]
 [1. 1.]]
