# Python basics

## Comments

In [26]:
# Shorter one line comment
""" Longer 
    multi-line 
    comment """

' Longer \n    multi-line \n    comment '

## Variables

In [27]:
x = 2 # variable assignment
x # display output - direct Expression
print(x) # display output - print function
x = 3 # variable reassignment
X = 4 # case sensitive
print(x+X) 

# Acceptable variable name formats
height = 5 
Height = 5
height1 = 5
height_ = 5 
height1_ = 5
height_1 = 5 
_height = 5 # Private variables usually start with an underscore
HEIGHT = 5 # Constansts are usually in uppercase
""" Invalid variable name formats - starting with a number, containing spaces, or special characters
1height = 5
height- = 5
height 1 = 5 """

2
7


' Invalid variable name formats - starting with a number, containing spaces, or special characters\n1height = 5\nheight- = 5\nheight 1 = 5 '

## Basic operations

In [28]:
print("2" + "3") # joining strings
print(2 + 3) # Addition
print(2 - 3) # Subtraction
print(2 * 3) # Multiplication
print(2 / 3) # Division
print(2 ** 3) # Exponentiation
print(2 % 3) # Modulus/remainder
print(2 // 3) # Floor division/quotient
print(2 == 3) # Comparison
print(x + X) # Mathematical operations on variables

23
5
-1
6
0.6666666666666666
8
2
0
False
7


## Data types

In [29]:
print(type(-2)) # Integer - whole numbers
print(type(2.0)) # Float - decimal numbers
print(type("2")) # String - text
print(type('2')) # String - text
print(type([2, 3])) # List- ordered collections of items.
print(type((2, 3))) # Tuple - ordered, immutable collections of items.
print(type({2, 3})) # Set - unordered collections of unique items.
print(type({'a': 2, 'b': 3})) # Dictionary - unordered collections of key-value pairs.  
print(type(True)) # Boolean - logical value indicating True or False.
print(type(None)) # NoneType - special type representing the absence of a value.
print(type(2 + 3j)) # Complex - numbers with a real and imaginary part
print(type(b'hello')) # Bytes - immutable sequences of bytes used for binary data

<class 'int'>
<class 'float'>
<class 'str'>
<class 'str'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'dict'>
<class 'bool'>
<class 'NoneType'>
<class 'complex'>
<class 'bytes'>


### Lists - a compound data type
#### Create a list

In [30]:
hall = 15.25
kit = 19.0
liv = 27
bed = 10.90
bath = 9.56
# Creating a simple list
area = [hall, kit, liv, bed, bath]
print(area)
# Create lists with different data types
area = ["hallway", hall, 
        "kitchen", kit, 
        "living", liv, 
        "bedroom", bed, 
        "bathroom", bath]
print(area)
# List of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living", liv],
         ["bedroom", bed],
         ["bathroom", bath]]
print(house)

[15.25, 19.0, 27, 10.9, 9.56]
['hallway', 15.25, 'kitchen', 19.0, 'living', 27, 'bedroom', 10.9, 'bathroom', 9.56]
[['hallway', 15.25], ['kitchen', 19.0], ['living', 27], ['bedroom', 10.9], ['bathroom', 9.56]]


#### Indexing and Subsetting lists

In [31]:
area = ['hallway', 15.25, 
        'kitchen', 19.0, 
        'living', 27, 
        'bedroom', 10.9, 
        'bathroom', 9.56]
# Accessing elements in a list - indexing
print(area[0])
print(area[-1])
print(area[5])

# Slicing a list - selecting multiple elements
print(area[2:5])
print(area[:6])
print(area[6:])

house = [['hallway', 15.25], 
         ['kitchen', 19.0], 
         ['living', 27], 
         ['bedroom', 10.9], 
         ['bathroom', 9.56]]

# Subsetting lists of lists
print(house[1][0])
print(house[1][:])

#subsettting and copying lists
house = area[:]
downstairs = area[:6]
upstairs = area[6:]
print(house)
print(downstairs)
print(upstairs)

hallway
9.56
27
['kitchen', 19.0, 'living']
['hallway', 15.25, 'kitchen', 19.0, 'living', 27]
['bedroom', 10.9, 'bathroom', 9.56]
kitchen
['kitchen', 19.0]
['hallway', 15.25, 'kitchen', 19.0, 'living', 27, 'bedroom', 10.9, 'bathroom', 9.56]
['hallway', 15.25, 'kitchen', 19.0, 'living', 27]
['bedroom', 10.9, 'bathroom', 9.56]


#### Modifying list elements

In [32]:
area = ['hallway', 15.25, 
        'kitchen', 19.0, 
        'living', 27, 
        'bedroom', 10.9, 
        'bathroom', 9.56]
print(area)
# replacing elements in a list
area[-1] = 10.5
area[4] = "chill zone"
print(area)

# Adding elements to a list
area = area + ["poolhouse", 24.5]
area_1 = area + ["garage", 15.45]
print(area)
print(area_1)

# Removing elements from a list
del(area[-2:])
del(area_1[10:12])
print(area)
print(area_1)


['hallway', 15.25, 'kitchen', 19.0, 'living', 27, 'bedroom', 10.9, 'bathroom', 9.56]
['hallway', 15.25, 'kitchen', 19.0, 'chill zone', 27, 'bedroom', 10.9, 'bathroom', 10.5]
['hallway', 15.25, 'kitchen', 19.0, 'chill zone', 27, 'bedroom', 10.9, 'bathroom', 10.5, 'poolhouse', 24.5]
['hallway', 15.25, 'kitchen', 19.0, 'chill zone', 27, 'bedroom', 10.9, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]
['hallway', 15.25, 'kitchen', 19.0, 'chill zone', 27, 'bedroom', 10.9, 'bathroom', 10.5]
['hallway', 15.25, 'kitchen', 19.0, 'chill zone', 27, 'bedroom', 10.9, 'bathroom', 10.5, 'garage', 15.45]


#### Concept of list references

In [33]:
area = [15.25, 19.0, 27, 10.9, 9.56]
area1 = area # Copying a list by reference
del(area1[0]) # Affects the original list
print(area)

area = [15.25, 19.0, 27, 10.9, 9.56]
area1 = area[:] # Copying a list by value
del(area1[0]) # Dies not affect the original list
print(area)

[19.0, 27, 10.9, 9.56]
[15.25, 19.0, 27, 10.9, 9.56]


## Functions
##### Functions are independent blocks of code that perform specific tasks and can be called without being associated with any object.

In [34]:
area = [15.25, 19.0, 27, 10.9, 9.56]
Bool = True
print(type(area))
print(len(area))
out2 = int(Bool)
print(out2)

# check documentation of a function
help(len)

# sorting a list
print(sorted(area))
print(sorted(area, reverse = True))


<class 'list'>
5
1
Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.

[9.56, 10.9, 15.25, 19.0, 27]
[27, 19.0, 15.25, 10.9, 9.56]


## Methods
##### Methods are functions associated with objects, allowing them to access and modify the object's attributes. They are called on instances of a class.

In [35]:
area = [15.25, 19.0, 27, 10.9, 9.56]
area.append(24.5)
print(area)
area.reverse()
print(area)
area.sort()
print(area)
area.index(27)

text = "python"
text = text.capitalize()
print(text)
text = text.upper()
print(text)
text.count('T')


[15.25, 19.0, 27, 10.9, 9.56, 24.5]
[24.5, 9.56, 10.9, 27, 19.0, 15.25]
[9.56, 10.9, 15.25, 19.0, 24.5, 27]
Python
PYTHON


1

## Packages
##### Packages are collections of modules that are grouped together to provide specific functionality. They help organize and manage code, making it easier to reuse and maintain.

In [36]:
import math

print(math.pi)
print(math.sqrt(25))
print(math.pow(2, 3))

circle_area = math.pi * 2 ** 2
circle_area = round(circle_area, 2)
print("area of the circle is " + str(circle_area) + "m^2")


3.141592653589793
5.0
8.0
area of the circle is 12.57m^2


#### Drawback of the list

In [37]:
height = [1.73, 1.68, 1.71, 1.89, 1.79] 
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
BMI = weight[0]/height[0]**2
print(BMI)
BMI = weight / height ** 2 # Will Throw error

21.85171572722109


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

### Numpy - Numeric Python

In [38]:
import numpy as np
np_height = np.array([1.65, 1.8, 1.45, 1.34, 1.8])
print("height", np_height)
np_weight = np.array([62.4, 55.2, 51.6, 48.4, 98.7])
print("weight", np_weight)
BMI = np_weight / np_height ** 2
print("BMI", np.round(BMI, 2)) # Will not throw error


height [1.65 1.8  1.45 1.34 1.8 ]
weight [62.4 55.2 51.6 48.4 98.7]
BMI [22.92 17.04 24.54 26.95 30.46]


#### Keep in mind


In [39]:
Array = np.array([1, 2.0, True, "hello"])
print(Array) # Will convert all elements to string
print(type(Array))

Array = np.array([1, 2.0, 3, 4]) # converts to float
print(Array) 
List = [1, 2.0, 3, 4]
print(Array + Array) #Adds elements
print(List + List) #Concatenates elements

['1' '2.0' 'True' 'hello']
<class 'numpy.ndarray'>
[1. 2. 3. 4.]
[2. 4. 6. 8.]
[1, 2.0, 3, 4, 1, 2.0, 3, 4]


#### Indexing and subsetting 1D numpy arrays

In [ ]:
Array = np.array([1, 2, 3, 4]) #1D array
print(Array[1])
print(Array[1:3])
print(Array[1:])
print(Array[:3])
print(Array>3)
print(Array[Array>2])

2
[2 3]
[2 3 4]
[1 2 3]
[False False False  True]
[3 4]


In [51]:
Array = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8]]) # 2D array
print(Array[0][2])
print(Array[0, 2])
print(Array[0, :])
print(Array[:, 2])
print(Array[:, 1:3])

3
3
[1 2 3 4]
[3 7]
[[2 3]
 [6 7]]


#### method vs attribute

In [50]:
Array = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8]]) # 2D array
print(np.mean(Array)) # Function from np module
print(Array.mean()) # Method of the array object
print(np.shape(Array)) # Attribute accessed via a method
print(Array.shape) #Directly accessing the attribute


4.5
4.5
(2, 4)
(2, 4)


#### Mathematical operations on arrays

In [59]:
Array = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8]]) # 2D array
var = np.array([3, 4, 5, 6])
print(Array * var)
print(Array * 10)
print(np.mean(Array, axis = 0)) # Column wise mean
print(np.mean(Array, axis = 1)) # Row wise mean
print(np.mean(Array, axis = None)) # Entire array mean


[[ 3  8 15 24]
 [15 24 35 48]]
[[10 20 30 40]
 [50 60 70 80]]
[3. 4. 5. 6.]
[2.5 6.5]
4.5


#### Basic statistical summary

In [70]:
Array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8]]) # 2D array  
print(np.mean(Array)) # Entire array mean
print(np.mean(Array[0, :])) # 1st row mean
print(np.mean(Array, axis = 1)) # Row wise mean
print(np.mean(Array, axis = 0)) # Column wise mean
print(np.median(Array)) # Median
print(np.std(Array)) # Standard deviation
print(np.corrcoef(Array[0, :], Array[1,:])) # Correlation coefficient between rows

4.5
2.5
[2.5 6.5]
[3. 4. 5. 6.]
4.5
2.29128784747792
[[1. 1.]
 [1. 1.]]
